openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    post:
      summary: ユーザー登録
      description: 新規ユーザーがシステムにサインアップする。
      requestBody:
        $ref: './components.yml#/components/requestBodies/UserRegistration'
      responses:
        '201':
          $ref: './components.yml#/components/responses/UserCreated'
        '400':
          $ref: './components.yml#/components/responses/BadRequest'
  /users/login:
    post:
      summary: ユーザー認証
      description: 既存のユーザーがシステムにログインする。
      requestBody:
        $ref: './components.yml#/components/requestBodies/UserLogin'
      responses:
        '200':
          $ref: './components.yml#/components/responses/SuccessfulLogin'
        '400':
          $ref: './components.yml#/components/responses/BadRequest'
        '401':
          $ref: './components.yml#/components/responses/Unauthorized'
  /users/{userId}:
    get:
      summary: ユーザー情報の取得
      description: ユーザーが自身のプロフィール情報を取得する。
      parameters:
        - $ref: './components.yml#/components/parameters/userId'
      responses:
        '200':
          $ref: './components.yml#/components/responses/SuccessfulGetUser'
        '404':
          $ref: './components.yml#/components/responses/NotFound'
    put:
      summary: ユーザー情報の更新
      description: ユーザーが自身のプロフィール情報を更新する。
      parameters:
        - $ref: './components.yml#/components/parameters/userId'
      requestBody:
        $ref: './components.yml#/components/requestBodies/UserUpdate'
      responses:
        '200':
          $ref: './components.yml#/components/responses/SuccessfulUpdateUser'
        '400':
          $ref: './components.yml#/components/responses/BadRequest'
        '404':
          $ref: './components.yml#/components/responses/NotFound'
    delete:
      summary: ユーザー情報の削除
      description: ユーザーが自身のアカウントを削除する。
      parameters:
        - $ref: './components.yml#/components/parameters/userId'
      responses:
        '204':
          $ref: './components.yml#/components/responses/SuccessfulDeleteUser'
        '404':
          $ref: './components.yml#/components/responses/NotFound'
